name: Self-Hosted

on:
  push:
    branches: [ master ]
  workflow_dispatch:

env:
  build_dir: "build"

jobs:
  build:
    name: Build ${{ matrix.os }} GCC ${{ matrix.gcc }} CUDA ${{ matrix.cuda }}
    runs-on: self-hosted
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-24.04
            cuda: "12.8"
            gcc: 13
    env:
      config: "Release"

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set environment variables
        run: |
          echo "CUDA_PATH=/usr/local/cuda-12.8" >> $GITHUB_ENV
          echo "${CUDA_PATH}/bin" >> $GITHUB_PATH
          echo "LD_LIBRARY_PATH=${CUDA_PATH}/lib64:${LD_LIBRARY_PATH}" >> $GITHUB_ENV
          echo "CC=/usr/bin/gcc-${{ matrix.gcc }}" >> $GITHUB_ENV
          echo "CXX=/usr/bin/g++-${{ matrix.gcc }}" >> $GITHUB_ENV
          echo "CUDAHOSTCXX=/usr/bin/g++-${{ matrix.gcc }}" >> $GITHUB_ENV
          echo "CUDACXX=/usr/local/cuda-${{ matrix.cuda }}/bin/nvcc" >> $GITHUB_ENV

      - name: Configure CMake build
        run: cmake . -B ${{ env.build_dir }} -DCMAKE_BUILD_TYPE=${{ env.config }} -DCUBOOL_BUILD_TESTS=ON

      - name: Build library sources
        working-directory: ${{ env.build_dir }}
        run: cmake --build . --target all --verbose -j `nproc`

  test:
    name: Test GPU ${{ matrix.gpu }} CUDA ${{ matrix.cuda }}
    needs: build
    runs-on: self-hosted
    env:
      unit-test-file: gpu_test_all.log
      regression-test-file: gpu_test_regression.log
    strategy:
      fail-fast: false
      matrix:
        include:
          - gpu: NVIDIA-GeForce-GT-1030
            cuda: "12.9"

    steps:
      - name: Run unit-tests
        working-directory: ${{ env.build_dir }}
        run: |
          source scripts/run_tests_all.sh | tee ${{ env.unit-test-file }}

      - name: Upload unit tests resutls
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.unit-test-file }}
          path: ${{ env.build_dir }}/${{ env.unit-test-file }}

      - name: Check for unit tests results
        working-directory: ${{ env.build_dir }}
        run: |
          if grep -q "FAILED" ${{ env.unit-test-file }}; then
            exit 1
          fi

      - name: Run regression-tests
        working-directory: ${{ env.build_dir }}/python
        run: |
          source run_tests.sh 2>&1 | tee ${{ env.regression-test-file }}

      - name: Upload regression tests resutls
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.regression-test-file }}
          path: ${{ env.build_dir }}/python/${{ env.regression-test-file }}

      - name: Check for regression tests results
        working-directory: ${{ env.build_dir }}/python
        run: |
          if grep -q "FAILED" ${{ env.regression-test-file }}; then
            exit 1
          fi

  clean:
    name: Cleanup workspace
    needs: test
    if: always()
    runs-on: self-hosted

    steps:
      - name: Cleanup workspace
        run: |
          rm -rf ${{ github.workspace }}/*
          rm -rf ${{ github.workspace }}/.*
