# Original script from https://github.com/ptheywood/cuda-cmake-github-actions

name: Self-Hosted

on:
  push:
    branches: [ master, self-hosted-runner ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

env:
  build_dir: "build"
  config: "Release"

jobs:
  build:
    name: Build ${{ matrix.os }} GCC ${{ matrix.gcc }} CUDA ${{ matrix.cuda }}
    runs-on: self-hosted
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-24.04
            cuda: "12.8"
            gcc: 13

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set environment variables
        run: |
          echo "CUDA_PATH=/usr/local/cuda-12.8" >> $GITHUB_ENV
          echo "${CUDA_PATH}/bin" >> $GITHUB_PATH
          echo "LD_LIBRARY_PATH=${CUDA_PATH}/lib64:${LD_LIBRARY_PATH}" >> $GITHUB_ENV
          echo "ะกะก=/usr/bin/gcc-${{ matrix.gcc }}" >> $GITHUB_ENV
          echo "CXX=/usr/bin/g++-${{ matrix.gcc }}" >> $GITHUB_ENV
          echo "CUDAHOSTCXX=/usr/bin/g++-${{ matrix.gcc }}" >> $GITHUB_ENV
          echo "CUDACXX=/usr/local/cuda-${{ matrix.cuda }}/bin/nvcc" >> $GITHUB_ENV

      - name: Configure CMake build
        run: cmake . -B ${{ env.build_dir }} -DCMAKE_BUILD_TYPE=${{ env.config }} -DCUBOOL_BUILD_TESTS=ON

      - name: Build library sources
        working-directory: ${{ env.build_dir }}
        run: cmake --build . --target all --verbose -j `nproc`
    
  test:
    name: Test ${{ matrix.os }} GCC ${{ matrix.gcc }} CUDA ${{ matrix.cuda }}
    needs: build
    runs-on: self-hosted
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-24.04
            cuda: "12.8"
            gcc: 13

    steps:
      - name: Run unit-tests
        id: unit-test
        working-directory: ${{ env.build_dir }}
        run: bash scripts/run_tests_fallback.sh
        shell: bash

      - name: Run regression-tests
        id: regression-test
        working-directory: ${{ env.build_dir }}/python
        run: bash run_tests.sh
        shell: bash

      - name: Return test code
        if: ${{ steps.unit-test.outcome == 'failure' || steps.regression-test.outcome == 'failure' }}
        run: exit 1
