# Original script from https://github.com/ptheywood/cuda-cmake-github-actions

name: Ubuntu

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

env:
  build_dir: "build"

jobs:
  build:
    name: Build ${{ matrix.os }} GCC ${{ matrix.gcc }} CUDA ${{ matrix.cuda }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-22.04
            cuda: "11.7"
            gcc: 9
    env:
      config: "Release"
      artifact: "cubool-ubuntu-build.tar.xz"

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Configure CMake build
        shell: bash
        run: cmake . -B ${{ env.build_dir }} -DCMAKE_BUILD_TYPE=${{ env.config }} -DCUBOOL_BUILD_TESTS=ON -DCUBOOL_WITH_CUDA=OFF

      - name: Build library sources
        working-directory: ${{ env.build_dir }}
        shell: bash
        run: cmake --build . --target all --verbose -j `nproc`

      - name: Prepare upload binary
        shell: bash
        run: tar cfz ${{ env.artifact }} ${{ env.build_dir }}

      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.artifact }}
          path: ${{ env.artifact }}

  test:
    name: Test CPU ${{ matrix.cpu }}
    needs: build
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-22.04
            cpu: AMD-EPYC-7763
    env:
      unit-test-file: cpu_test_all.log
      regression-test-file: cpu_test_regression.log

    steps:
      - name: Run unit-tests
        working-directory: ${{ env.build_dir }}
        shell: bash
        run: |
          source scripts/run_tests_all.sh | tee ${{ env.unit-test-file }}

      - name: Upload unit tests resutls
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.unit-test-file }}
          path: ${{ env.build_dir }}/${{ env.unit-test-file }}

      - name: Check for unit tests results
        working-directory: ${{ env.build_dir }}
        shell: bash
        run: |
          if grep -q "FAILED" ${{ env.unit-test-file }}; then
            exit 1
          fi

      - name: Run regression-tests
        working-directory: ${{ env.build_dir }}/python
        shell: bash
        run: |
          source run_tests.sh 2>&1 | tee ${{ env.regression-test-file }}

      - name: Upload regression tests resutls
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.regression-test-file }}
          path: ${{ env.build_dir }}/python/${{ env.regression-test-file }}

      - name: Check for regression tests results
        working-directory: ${{ env.build_dir }}/python
        shell: bash
        run: |
          if grep -q "FAILED" ${{ env.regression-test-file }}; then
            exit 1
          fi
